var chosenEntry=null,LogoCheck=document.querySelector("#ChkLogo"),TypeCheck=document.querySelector("#ChkType"),SizeCheck=document.querySelector("#ChkSize"),LogoButton=document.querySelector("#choose_logo"),Type="",Size="",FontSelect="sans-serif",chooseFileButton=document.querySelector("#choose_file"),chooseDirButton=document.querySelector("#choose_dir"),PhotoAmount="",ClearPicturesButton=document.querySelector("#btnClearImages"),ClearAllButton=document.querySelector("#btnClearAll"),savePNGButton=
document.querySelector("#save_PNG"),saveJPGButton=document.querySelector("#save_JPG"),RunButton=document.querySelector("#btnRun"),entries=[],CropImages=[],croppers=[],images=new Image,canvas=document.querySelector("canvas"),canvasContext=canvas.getContext("2d"),image_display=document.querySelector("#image_display"),img=new Image,croped=[],WatermarkText="",Font="",FontSize="",TextColor="#fff",body=$("body"),Orientation="";function errorHandler(a){console.error(a)}
function displayEntryData(a){a.isFile?(chrome.fileSystem.getDisplayPath(a,function(a){document.querySelector("#file_path").value=a}),a.getMetadata(function(a){document.querySelector("#file_size").textContent=a.size})):(document.querySelector("#file_path").value=a.fullPath,document.querySelector("#file_size").textContent="N/A")}
function writeFileEntry(a,b,d){a?a.createWriter(function(a){a.onerror=errorHandler;a.onwriteend=d;b?(a.truncate(b.size),waitForIO(a,function(){a.seek(0);a.write(b)})):chosenEntry.file(function(b){a.truncate(b.fileSize);waitForIO(a,function(){a.seek(0);a.write(b)})})},errorHandler):output.textContent="Nothing selected."}
function waitForIO(a,b){var d=Date.now(),e=function(){a.readyState===a.WRITING&&4E3>Date.now()-d?setTimeout(e,100):a.readyState===a.WRITING?(console.error("Write operation taking too long, aborting! (current writer readyState is "+a.readyState+")"),a.abort()):b()};setTimeout(e,100)}function loadLogoEntry(a){chosenEntry=a;chosenEntry.file(function(a){loadLogoFromFile(a);displayfileEntryPath(chosenFileEntry)})}
function loadLogoFromFile(a){ResizeBlob=ResizeLogo(a).then(function(a){console.log(ResizeBlob)})}function loadImageFromFile(a){ResizeImage(a).then(function(a){})}function loadLogoFromURL(a){clearState();img.onload=LogoHasLoaded;img.onerror=LogoHasLoaded;img.src=a}function loadImageFromURL(a){images.src=a;entries.push(images.src)}
function resetOrientation(a,b,d){var e=new Image;e.onload=function(){var a=e.width,f=e.height,k=document.createElement("canvas"),g=k.getContext("2d");-1<[5,6,7,8].indexOf(b)?(k.width=f,k.height=a):(k.width=a,k.height=f);switch(b){case 2:g.transform(-1,0,0,1,a,0);break;case 3:g.transform(-1,0,0,-1,a,f);break;case 4:g.transform(1,0,0,-1,0,f);break;case 5:g.transform(0,1,1,0,0,0);break;case 6:g.transform(0,1,-1,0,f,0);break;case 7:g.transform(0,-1,-1,0,f,a);break;case 8:g.transform(0,-1,1,0,0,a);break;
default:g.transform(1,0,0,1,0,0)}g.drawImage(e,0,0);console.log("203");d(k.toDataURL())};e.src=a}function ResizeLogo(a){console.log("ResizeImage");ImageTools.resize(a,{width:200,height:200},function(a,d){console.log(d);loadLogoFromURL(URL.createObjectURL(a))})}
function GetOrientation(a,b){console.log("228");var d=new FileReader;d.onload=function(a){a=new DataView(a.target.result);if(65496!=a.getUint16(0,!1))return b(-2);for(var d=a.byteLength,f=2;f<d;){var e=a.getUint16(f,!1);f+=2;if(65505==e){if(1165519206!=a.getUint32(f+=2,!1))break;e=18761==a.getUint16(f+=6,!1);f+=a.getUint32(f+4,e);var g=a.getUint16(f,e);f+=2;for(var l=0;l<g;l++)if(274==a.getUint16(f+12*l,e))return b(a.getUint16(f+12*l+8,e))}else if(65280!=(e&65280))break;else f+=a.getUint16(f,!1)}return b(-1)};
d.readAsArrayBuffer(a)}var c=0;
function ResizeImage(a){console.log("ResizeImage");GetOrientation(a,function(b){ImgOrientation=b;console.log("272 "+ImgOrientation);ImageTools.resize(a,{width:720,height:960},function(b,e){blobBase64=window.URL.createObjectURL(b);resetOrientation(blobBase64,ImgOrientation,function(b){console.log("274");loadImageFromURL(b);cropsrc=window.URL.createObjectURL(a);$("#cropdiv").prepend('<img id="crop" src="'+cropsrc+'" />');var d=document.querySelectorAll("#crop"),e=d.length;for(i=0;i<e;i++)croppers.push(new Cropper(d[i],
{autoCropArea:.2,ready:function(){this.cropper.zoom(.3);console.log(this);this.cropper.setCropBoxData({width:125,height:125});c++;console.log(PhotoAmount);console.log(c);base64=this.cropper.getCroppedCanvas({width:150,height:150}).toDataURL();$("#cropeddiv").prepend('<img id="croped" src="'+base64+'"/>');$("#imgresized").prepend('<img id="finalimg" src="'+b+'" />');PhotoAmount==c&&(HideDiv(),body.removeClass("loading"))}}))})})})}function HideDiv(){$("#cropdiv").hide()}
function LogoHasLoaded(){img.width&&img.height||displayText("Image failed to load.");drawCanvas()}function imageHasLoaded(){images.width&&images.height||displayText("Image failed to load.");drawCanvasWatermark()}function displayfileEntryPath(a){chrome.fileSystem.getDisplayPath(a,displayText)}function displayText(a){output.textContent=a}function clearState(){img.src="";drawCanvas()}
function drawCanvas(){canvas.width=canvas.clientWidth;canvas.height=canvas.clientHeight;img.width&&img.height&&canvas.width&&canvas.height&&canvasContext.drawImage(img,0,0,100,100*img.height/img.width)}
function loadDirEntry(a,b){chosenEntry=a;if(chosenEntry.isDirectory){var d=chosenEntry.createReader(),e=function(){d.readEntries(function(a){a.length?(PhotoAmount=a.length,a.forEach(function(a){a.isDirectory?(console.log("Directory found - Skipping over it - "+a),new Notification("Directory found",{body:"Please only include photos in your directory",icon:"../images/AppIcon.png"})):a.file(function(a){loadImageFromFile(a)})}),e()):displayEntryData(chosenEntry)},errorHandler)};e()}}
function CropAction(){var a=document.querySelectorAll("#crop"),b=a.length,d;for(d=0;d<b;d++)base64=a[d].cropper.getCroppedCanvas({width:125,height:125}).toDataURL(),$("#croped").prepend('<img id="croped" src="'+base64+'"/>'),CropImages.push(base64)}
function MakeZoomedImage(a){body.addClass("loading");$.each(entries,function(a,d){var b=document.querySelectorAll("#finalimg"),h=document.querySelectorAll("#croped"),f=$("<div id='container"+a+"' class='WatermarkPhotoContainer'></div>");$("#watermarked").append(f);watermark([b[a].src,img]).image(watermark.image.upperRight()).render().image(watermark.text.upperLeft(WatermarkText,FontSize+"px "+FontSelect,TextColor,0,48)).load([h[a].src]).image(watermark.image.lowerLeft()).then(function(b){return document.getElementById("container"+
a).appendChild(b).setAttribute("class","WatermarkPhoto materialboxed responsive-img")})});return a(1)}function convertImageToCanvas(a,b){var d=document.getElementById("JPG"+a),e=d.getContext("2d"),h=new Image;h.onload=function(){e.drawImage(this,0,0,d.width,d.height)};h.src=b;d.width=h.width;d.height=h.height;return d}
$(document).ready(function(){$("#showPalette").spectrum({showPalette:!0,palette:[["#FED141","#FF9D6E","#F67599"],["#DD7FD3","#9595D2","#8BB8E8"],["#64CCC9","#888B8D"]],change:function(a){TextColor=a.toHexString();console.log(TextColor)}});$("#SlideFontSize").slider({min:10,max:120,step:1,value:48,orientation:"horizontal"});$(".style a").click(function(){Type=$(this).text();$("#StyleChose").html(Type);console.log(Type)});$(".size a").click(function(){Size=$(this).text();$("#SizeChose").html(Size);
console.log(Size)});$(".font a").click(function(){FontSelect=$(this).text();$("<style> .fontface{font-family:'"+FontSelect+"';} </style>").appendTo(document.head);$("#FontChose").html(FontSelect)})});
LogoButton.addEventListener("click",function(a){$("#LogoCanvas").fadeIn("fast");chrome.fileSystem.chooseEntry({type:"openFile",accepts:[{mimeTypes:["image/*"],extensions:["jpeg","png"]}]},function(a){a?(chrome.storage.local.set({chosenFile:chrome.fileSystem.retainEntry(a)}),loadLogoEntry(a)):output.textContent="No image selected."})});
chooseDirButton.addEventListener("click",function(a){chrome.fileSystem.chooseEntry({type:"openDirectory"},function(a){body.addClass("loading");a?(chrome.storage.local.set({chosenFile:chrome.fileSystem.retainEntry(a)}),loadDirEntry(a)):body.removeClass("loading")})});
savePNGButton.addEventListener("click",function(a){a=new JSZip;var b=a.folder("images");$(".WatermarkPhoto").each(function(a){imgsrc=this.src;var d=imgsrc.replace("data:image/png;base64,","");b.file(a+".png",d,{base64:!0})});a.generateAsync({type:"blob"}).then(function(a){saveAs(a,WatermarkText+".zip")})});
saveJPGButton.addEventListener("click",function(a){var b=new JSZip;var d=""==WatermarkText?b.folder("images"):b.folder(WatermarkText);$(".WatermarkPhoto").each(function(a){$("#JPGContainer").prepend('<canvas id="JPG'+a+'" />');imgsrc=this.src;var b=convertImageToCanvas(a,imgsrc);$("#JPGContainer").imagesLoaded(function(){var e=b.toDataURL("image/jpeg").replace("data:image/jpeg;base64,","");d.file(WatermarkText+a+".jpg",e,{base64:!0})})});$("#JPGContainer").imagesLoaded(function(){b.generateAsync({type:"blob"}).then(function(a){saveAs(a,
WatermarkText+".zip")})})});
RunButton.addEventListener("click",function(a){$("#watermarked").fadeIn("fast");""!==Type&&""!==Size?(console.log("type and size"),WatermarkText=Type+" - "+Size,console.log(WatermarkText)):""==Type&&""!==Size?(console.log("size"),WatermarkText=Size,console.log(WatermarkText)):""!==Type&&""==Size&&(console.log("type"),WatermarkText=Type,console.log(WatermarkText));FontSize=$("#SlideFontSize").slider("getValue");MakeZoomedImage(function(a){body.removeClass("loading")});savePNGButton.disabled=!1;saveJPGButton.disabled=
!1;chooseDirButton.disabled=!0});
ClearPicturesButton.addEventListener("click",function(a){chrome.storage.local.remove(["chosenFile"],function(){var a=chrome.runtime.lastError;a&&console.error(a)});entries=[];CropImages=[];Croppers=[];c=PhotoAmount=0;document.getElementById("file_path").value="";$("#watermarked").empty();$("#watermarked").hide();$("#cropdiv").empty();$("#cropeddiv").empty();$("#imgresized").empty();$("#cropdiv").show();$("#JPGContainer").empty();savePNGButton.disabled=!0;saveJPGButton.disabled=!0;$("#btnRun").disabled=
!1;chooseDirButton.disabled=!1});
ClearAllButton.addEventListener("click",function(a){chrome.storage.local.remove(["chosenFile"],function(){var a=chrome.runtime.lastError;a&&console.error(a)});entries=[];CropImages=[];Croppers=[];Type=document.getElementById("file_path").value="";$("#StyleChose").html("");Size="";$("#SizeChose").html("");FontSelect="";$("#FontChose").html("");canvasContext.clearRect(0,0,canvas.width,canvas.height);$("#watermarked").empty();$("#watermarked").hide();$("#cropdiv").empty();$("#cropeddiv").empty();$("#imgresized").empty();
$("#cropdiv").show();$("#JPGContainer").empty();savePNGButton.disabled=!0;saveJPGButton.disabled=!0;$("#btnRun").disabled=!1;chooseDirButton.disabled=!1});
